### ISSUE TITLE
The Tao tokens are not being credited

### ISSUE THREAD

**Issue by nepaldude** [taoblockchain/tao-core#1]
I sent 1 bitcoin to this address
37vDQv56cA7XK7x7TFAy95JAHMSHhUPCei

Tao tokens were supposed to be deposited in the following address. What happened?
TjW6bmUBwZsPWxc9JoeVbMkLgxaTE3tdDN

**Comment by abhayo1990** [comment]
my tokens also not shown... what to do now

**Comment by taoblockchain** [comment]
Tokens will be distributed within 96 hours after the end of the crowd sale as was stated on the website.
